# For more information: https://laravel.com/docs/sail
version: '3'
services:

  laravel.test:
    build:
      context: ./docker/dockerfiles/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-root}'
    image: sail-8.0/app
    ports:
      - '${APP_PORT:-8010}:80'
    environment:
      WWWUSER: '${WWWUSER:-root}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-8012}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './docker/services/mysql/${DB_DATABASE}:/var/lib/mysql'
    networks:
      - sail

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '${PHPMYADMIN_PORT:-8013}:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: '${DB_HOST}'
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://phpmyadmin" ]
      interval: 1s
      timeout: 3s
      retries: 60
    depends_on:
      - mysql
    networks:
      - sail

networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
